### ISSUE TITLE
BigQuery Errors

### ISSUE THREAD

**Issue by CartWill** [OHDSI/DataQualityDashboard#98]
It looks like some errors are getting thrown in some of the date comparisons.  BigQuery will only compare two of the exact same type.  It looks like some of the casting was taken out recently: #92

```
BMS:
bigquery

Error:
java.sql.SQLException: [Simba]BigQueryJDBCDriver(100032) Error executing query job. Message: No matching signature for operator > for argument types: DATETIME, DATE. Supported signatures: ANY ANY at [10:11]

SQL:

/*********
PLAUSIBLE_VALUE_HIGH
get number of records and the proportion to total number of eligible records that exceed this threshold

Parameters used in this template:
cdmDatabaseSchema = uchealth_omop
cdmTableName = DEVICE_EXPOSURE
cdmFieldName = device_exposure_start_datetime
plausibleValueHigh = DATEADD(dd,1,GETDATE())
**********/

select num_violated_rows, case when denominator.num_rows = 0 then 0 else 1.0*num_violated_rows/denominator.num_rows end  as pct_violated_rows, 
  denominator.num_rows as num_denominator_rows
from
(
	select COUNT(violated_rows.violating_field) as num_violated_rows
	from
	(
		select 'DEVICE_EXPOSURE.device_exposure_start_datetime' as violating_field, cdmtable.*
    from uchealth_omop.device_exposure cdmtable
    where cdmtable.device_exposure_start_datetime > DATE_ADD(cast(CURRENT_DATE() as date), interval 1 DAY)
	) violated_rows
) violated_row_count,
(
	select COUNT(*) as num_rows
	from uchealth_omop.device_exposure
  where device_exposure_start_datetime is not null
) denominator
;
```

**Comment by clairblacketer** [comment]
yes, we had to take the casting out because it was done on the field name itself and it was throwing errors because CAST(...as date) is not a valid field name. This issue is on our list and we plan to incorporate a different way to cast those values to dates.

**Comment by alondhe** [comment]
Maybe we can pass in a parameter "castAsDate" and then use SqlRender if-then logic around the where clause to cast as date.

**Comment by alondhe** [comment]
Hi @CartWill -- pushed a fix to the develop branch. Can you try it out?

`remove.packages("DataQualityDashboard")`
restart R session
`devtools::install_github("OHDSI/DataQualityDashboard", ref = "develop")`

**Comment by CartWill** [comment]
That does seem like it takes care of that error.  Thank you!

When I was checking on the previous error, I noticed this one too.  It looks like it happens when the program tries to write the results to the resultsSchemaTable.  I don't see anything written to the results schema.  If I set writeToTable = FALSE, then I don't see that error.  
```
|=====================================================================================================================| 100%
Connecting using BigQuery driver
Execution Complete
Connecting using BigQuery driver
java.sql.SQLException: [Simba][BigQueryJDBCDriver](100036) Batched and streamed parameters not supported.
	at com.simba.googlebigquery.googlebigquery.dataengine.BQAbstractExecutor.clearPushedParamData(Unknown Source)
	at com.simba.googlebigquery.jdbc.common.SPreparedStatement.doClearBatch(Unknown Source)
	at com.simba.googlebigquery.jdbc.common.SPreparedStatement.clearBatch(Unknown Source)
	at com.simba.googlebigquery.jdbc.common.SPreparedStatement.executePreparedAnyBatch(Unknown Source)
	at com.simba.googlebigquery.jdbc.common.SPreparedStatement.executeBatch(Unknown Source)
Caused by: com.simba.googlebigquery.support.exceptions.GeneralException: [Simba][BigQueryJDBCDriver](100036) Batched and streamed parameters not supported.
	... 5 more
$startTimestamp
[1] "2020-03-06 12:16:35 MST"

$endTimestamp
[1] "2020-03-06 12:51:35 MST"

$executionTime
[1] "35 mins"
```

**Comment by alondhe** [comment]
@CartWill -- have you been able to use DatabaseConnector::insertTable with BigQuery? Because that's all the writeToTable logic is using in DQD.

**Comment by CartWill** [comment]
We've never tried to use that to insert a table before.  I can try to do that next week and see if it'll work.  Maybe one of the other options like useMppBulkLoad needs to be set differently to get it add.

**Comment by alondhe** [comment]
> We've never tried to use that to insert a table before. I can try to do that next week and see if it'll work. Maybe one of the other options like useMppBulkLoad needs to be set differently to get it add.

The useMppBulkLoad option is only for Redshift and MS PDW. You won't need it for BigQuery. Can you try using it with a small data frame just to confirm it works?

**Comment by CartWill** [comment]
I tried this out with a small dataframe from the command line and still get the same error. 

```
DatabaseConnector::insertTable(connection = connection, tableName = "results.testTable", data=df, createTable = TRUE, tempTable = FALSE)
java.sql.SQLException: [Simba][BigQueryJDBCDriver](100036) Batched and streamed parameters not supported.
	at com.simba.googlebigquery.googlebigquery.dataengine.BQAbstractExecutor.clearPushedParamData(Unknown Source)
	at com.simba.googlebigquery.jdbc.common.SPreparedStatement.doClearBatch(Unknown Source)
	at com.simba.googlebigquery.jdbc.common.SPreparedStatement.clearBatch(Unknown Source)
	at com.simba.googlebigquery.jdbc.common.SPreparedStatement.executePreparedAnyBatch(Unknown Source)
	at com.simba.googlebigquery.jdbc.common.SPreparedStatement.executeBatch(Unknown Source)
Caused by: com.simba.googlebigquery.support.exceptions.GeneralException: [Simba][BigQueryJDBCDriver](100036) Batched and streamed parameters not supported.
	... 5 more
```
